In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
c=np.array([[
    [1,2,3],[4,5,6],[8, 9,10],[11,12,13]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]
  [ 8  9 10]
  [11 12 13]]]


In [6]:
d=np.array([[
    [1,2,3],[4,5,6],[8, 9,10],[11,12,13],[14,15,16]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 8  9 10]
  [11 12 13]
  [14 15 16]]]


In [7]:
arr=np.zeros((4,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
arr=np.arange(1,15)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
arr=np.linspace(0,6,30)
print(arr)

[0.         0.20689655 0.4137931  0.62068966 0.82758621 1.03448276
 1.24137931 1.44827586 1.65517241 1.86206897 2.06896552 2.27586207
 2.48275862 2.68965517 2.89655172 3.10344828 3.31034483 3.51724138
 3.72413793 3.93103448 4.13793103 4.34482759 4.55172414 4.75862069
 4.96551724 5.17241379 5.37931034 5.5862069  5.79310345 6.        ]


In [11]:
arr=np.array([[
    [1,2,3],[4,5,6],[8, 9,10],[11,12,13]]])
print(arr[0,1],[2,3])

[4 5 6] [2, 3]


In [23]:
m=np.array([[1,2,3],
            [4,5,6]])
print(m[0,1])
print(m[1,2])

2
6


In [24]:
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [37]:
m=np.array([10,20,30,40])
print(m)
print(m[-1])
print(m[:3])
print(m[1:4])

[10 20 30 40]
40
[10 20 30]
[20 30 40]


In [38]:
print(arr.shape)

(2, 3)


In [39]:
print(arr.ndim)

2


In [40]:
print(arr.size)

6


In [41]:
print(arr.dtype)

float64


In [43]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[2])

10
30


In [44]:
print(arr[-1])

40


In [45]:
arr=np.array([10,20,30,40,50,60])
print(arr[1:4])

[20 30 40]


In [46]:
print(arr[:3])

[10 20 30]


In [48]:
print(arr[3:])

[40 50 60]


In [49]:
print(arr[::2])

[10 30 50]


In [51]:
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [52]:
arr=np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]
